default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_task_development
  username: postgres
  password: root
  host: localhost
  port: 5432


test:
  <<: *default
  database: ruby_task_test
  username: postgres
  password: root
  host: localhost
  port: 5432


production:
  <<: *default
  database: ruby_task_production
  username: ruby_task
  password: <%= ENV["RUBY_TASK_DATABASE_PASSWORD"] %>
